print('Computer: Hello !!!')
name = input('Computer: What is your name?\n - ')
print('Computer: Hello ' + name + '!!')
print('Computer: It is nice to meet you ' + name + '!!!')
print('Computer: How are you ' + name + '??')
input(name + ': ')