print('Loony: Hello !!!')
name = input('Loony: What is your name?\n - ')
print('Loony: Hello ' + name + '!!')
print('Loony: It is nice to meet you ' + name + '!!!')
print('Loony: How are you ' + name + '??')
input(name + ': ')